// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicFree;

#nullable disable

namespace MusicFree.Migrations
{
    [DbContext(typeof(FreeMusicContext))]
    [Migration("20240930130627_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicFree.Models.Albumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MusicianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("MusicianId");

                    b.ToTable("albumns");
                });

            modelBuilder.Entity("MusicFree.Models.Musician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("musicians");
                });

            modelBuilder.Entity("MusicFree.Models.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("song_filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumnId");

                    b.ToTable("songs");
                });

            modelBuilder.Entity("MusicFree.Models.SongAuthor", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuthorId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("SongAuthor");
                });

            modelBuilder.Entity("MusicFree.Models.Albumn", b =>
                {
                    b.HasOne("MusicFree.Models.Musician", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicFree.Models.Musician", null)
                        .WithMany("Albumns")
                        .HasForeignKey("MusicianId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MusicFree.Models.Song", b =>
                {
                    b.HasOne("MusicFree.Models.Albumn", "Albumn")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Albumn");
                });

            modelBuilder.Entity("MusicFree.Models.SongAuthor", b =>
                {
                    b.HasOne("MusicFree.Models.Musician", "Author")
                        .WithMany("Songs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicFree.Models.Song", "Song")
                        .WithMany("Authors")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MusicFree.Models.Albumn", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("MusicFree.Models.Musician", b =>
                {
                    b.Navigation("Albumns");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("MusicFree.Models.Song", b =>
                {
                    b.Navigation("Authors");
                });
#pragma warning restore 612, 618
        }
    }
}
