// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicFree;

#nullable disable

namespace MusicFree.Migrations
{
    [DbContext(typeof(FreeMusicContext))]
    [Migration("20250713173318_NewGenreTag")]
    partial class NewGenreTag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicFree.Models.Albumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Main_AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("albumn_type")
                        .HasColumnType("int");

                    b.Property<string>("cover_filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Main_AuthorId");

                    b.ToTable("albumns");
                });

            modelBuilder.Entity("MusicFree.Models.AlbumnAuthor", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuthorId", "AlbumnId");

                    b.HasIndex("AlbumnId");

                    b.ToTable("albumn_authors");
                });

            modelBuilder.Entity("MusicFree.Models.AlbumnViews", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("last_listened")
                        .HasColumnType("datetime2");

                    b.Property<int>("listened")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumnId");

                    b.ToTable("albumn_views");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.Genre", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("genres");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.GenreGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GenreName");

                    b.ToTable("similar_genre");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.GenreUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("genreName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("genre_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("last_listened")
                        .HasColumnType("datetime2");

                    b.Property<int>("listened")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("genreName");

                    b.ToTable("genreUsers");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.GenretoAlbumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("albumn_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("genre_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("albumn_id");

                    b.HasIndex("genre_id");

                    b.ToTable("genre_albumn");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.GenretoMusician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("author_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("genre_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("author_id");

                    b.HasIndex("genre_id");

                    b.ToTable("genre_musician");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.GenretoSong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("genre_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("song_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("genre_id");

                    b.HasIndex("song_id");

                    b.ToTable("genre_song");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.TagTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("similar_tag");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.TagUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("last_listened")
                        .HasColumnType("datetime2");

                    b.Property<int>("listened")
                        .HasColumnType("int");

                    b.Property<string>("tagName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tag_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("tagName");

                    b.ToTable("TagUser");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.Tags", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.TagtoAlbumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("albumn_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tag_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("albumn_id");

                    b.HasIndex("tag_id");

                    b.ToTable("tag_albumn");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.TagtoSong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("song_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tag_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("song_id");

                    b.HasIndex("tag_id");

                    b.ToTable("tag_song");
                });

            modelBuilder.Entity("MusicFree.Models.Musician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img_filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("musicians");
                });

            modelBuilder.Entity("MusicFree.Models.MusicianUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsersId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("musician_likes");
                });

            modelBuilder.Entity("MusicFree.Models.MusicianView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MusicianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MusicianId");

                    b.ToTable("userMusicians");
                });

            modelBuilder.Entity("MusicFree.Models.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("playlist");
                });

            modelBuilder.Entity("MusicFree.Models.PlaylistSong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("SongId");

                    b.ToTable("playlistSong");
                });

            modelBuilder.Entity("MusicFree.Models.SearchModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_albumn")
                        .HasColumnType("bit");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlbumnId");

                    b.HasIndex("AuthorId");

                    b.ToTable("searches");
                });

            modelBuilder.Entity("MusicFree.Models.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Main_AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("albumn_index")
                        .HasColumnType("int");

                    b.Property<string>("cover_filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("listened")
                        .HasColumnType("int");

                    b.Property<string>("song_filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumnId");

                    b.HasIndex("Main_AuthorId");

                    b.ToTable("songs");
                });

            modelBuilder.Entity("MusicFree.Models.SongAuthor", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuthorId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("song_authors");
                });

            modelBuilder.Entity("MusicFree.Models.SongViews", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("last_listened")
                        .HasColumnType("datetime2");

                    b.Property<int>("listened")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("songsViews");
                });

            modelBuilder.Entity("MusicFree.Models.UserAlbumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumnId");

                    b.ToTable("userAlbumns");
                });

            modelBuilder.Entity("MusicFree.Models.UserSong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("likes");
                });

            modelBuilder.Entity("TagTagTags", b =>
                {
                    b.Property<Guid>("similarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tagsName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("similarId", "tagsName");

                    b.HasIndex("tagsName");

                    b.ToTable("TagTagTags");
                });

            modelBuilder.Entity("MusicFree.Models.Albumn", b =>
                {
                    b.HasOne("MusicFree.Models.Musician", "Main_Author")
                        .WithMany("Albumns")
                        .HasForeignKey("Main_AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Main_Author");
                });

            modelBuilder.Entity("MusicFree.Models.AlbumnAuthor", b =>
                {
                    b.HasOne("MusicFree.Models.Albumn", "Albumn")
                        .WithMany("Extra_Authors")
                        .HasForeignKey("AlbumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicFree.Models.Musician", "Author")
                        .WithMany("collaboration_albumns")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Albumn");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MusicFree.Models.AlbumnViews", b =>
                {
                    b.HasOne("MusicFree.Models.Albumn", "albumn")
                        .WithMany("albumn_views")
                        .HasForeignKey("AlbumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("albumn");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.GenreGenre", b =>
                {
                    b.HasOne("MusicFree.Models.GenreAndName.Genre", null)
                        .WithMany("similar")
                        .HasForeignKey("GenreName");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.GenreUser", b =>
                {
                    b.HasOne("MusicFree.Models.GenreAndName.Genre", "genre")
                        .WithMany("users")
                        .HasForeignKey("genreName");

                    b.Navigation("genre");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.GenretoAlbumn", b =>
                {
                    b.HasOne("MusicFree.Models.Albumn", "albumn")
                        .WithMany("genres")
                        .HasForeignKey("albumn_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicFree.Models.GenreAndName.Genre", "genre")
                        .WithMany("albumns")
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("albumn");

                    b.Navigation("genre");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.GenretoMusician", b =>
                {
                    b.HasOne("MusicFree.Models.Musician", "author")
                        .WithMany("genres")
                        .HasForeignKey("author_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicFree.Models.GenreAndName.Genre", "genre")
                        .WithMany("authors")
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("author");

                    b.Navigation("genre");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.GenretoSong", b =>
                {
                    b.HasOne("MusicFree.Models.GenreAndName.Genre", "genre")
                        .WithMany("song")
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicFree.Models.Song", "song")
                        .WithMany("genres")
                        .HasForeignKey("song_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("genre");

                    b.Navigation("song");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.TagUser", b =>
                {
                    b.HasOne("MusicFree.Models.GenreAndName.Tags", "tag")
                        .WithMany("users")
                        .HasForeignKey("tagName");

                    b.Navigation("tag");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.TagtoAlbumn", b =>
                {
                    b.HasOne("MusicFree.Models.Albumn", "albumn")
                        .WithMany("tags")
                        .HasForeignKey("albumn_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicFree.Models.GenreAndName.Tags", "tag")
                        .WithMany("albumns")
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("albumn");

                    b.Navigation("tag");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.TagtoSong", b =>
                {
                    b.HasOne("MusicFree.Models.Song", "song")
                        .WithMany("tags")
                        .HasForeignKey("song_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicFree.Models.GenreAndName.Tags", "tag")
                        .WithMany("song")
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("song");

                    b.Navigation("tag");
                });

            modelBuilder.Entity("MusicFree.Models.MusicianUser", b =>
                {
                    b.HasOne("MusicFree.Models.Musician", "author")
                        .WithMany("liked_by")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("author");
                });

            modelBuilder.Entity("MusicFree.Models.MusicianView", b =>
                {
                    b.HasOne("MusicFree.Models.Musician", "author")
                        .WithMany("listened_by")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("author");
                });

            modelBuilder.Entity("MusicFree.Models.PlaylistSong", b =>
                {
                    b.HasOne("MusicFree.Models.Playlist", "Playlist")
                        .WithMany("songs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicFree.Models.Song", "Song")
                        .WithMany("playllists")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MusicFree.Models.SearchModel", b =>
                {
                    b.HasOne("MusicFree.Models.Albumn", "Albumn")
                        .WithMany()
                        .HasForeignKey("AlbumnId");

                    b.HasOne("MusicFree.Models.Musician", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Albumn");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MusicFree.Models.Song", b =>
                {
                    b.HasOne("MusicFree.Models.Albumn", "Albumn")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicFree.Models.Musician", "Main_Author")
                        .WithMany("Songs")
                        .HasForeignKey("Main_AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Albumn");

                    b.Navigation("Main_Author");
                });

            modelBuilder.Entity("MusicFree.Models.SongAuthor", b =>
                {
                    b.HasOne("MusicFree.Models.Musician", "Author")
                        .WithMany("collaboration_songs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicFree.Models.Song", "Song")
                        .WithMany("extra_authors")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MusicFree.Models.SongViews", b =>
                {
                    b.HasOne("MusicFree.Models.Song", "song")
                        .WithMany("song_views")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("song");
                });

            modelBuilder.Entity("MusicFree.Models.UserAlbumn", b =>
                {
                    b.HasOne("MusicFree.Models.Albumn", "Albumn")
                        .WithMany("liked_by")
                        .HasForeignKey("AlbumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Albumn");
                });

            modelBuilder.Entity("MusicFree.Models.UserSong", b =>
                {
                    b.HasOne("MusicFree.Models.Song", "Song")
                        .WithMany("liked_by")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("TagTagTags", b =>
                {
                    b.HasOne("MusicFree.Models.GenreAndName.TagTag", null)
                        .WithMany()
                        .HasForeignKey("similarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicFree.Models.GenreAndName.Tags", null)
                        .WithMany()
                        .HasForeignKey("tagsName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicFree.Models.Albumn", b =>
                {
                    b.Navigation("Extra_Authors");

                    b.Navigation("Songs");

                    b.Navigation("albumn_views");

                    b.Navigation("genres");

                    b.Navigation("liked_by");

                    b.Navigation("tags");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.Genre", b =>
                {
                    b.Navigation("albumns");

                    b.Navigation("authors");

                    b.Navigation("similar");

                    b.Navigation("song");

                    b.Navigation("users");
                });

            modelBuilder.Entity("MusicFree.Models.GenreAndName.Tags", b =>
                {
                    b.Navigation("albumns");

                    b.Navigation("song");

                    b.Navigation("users");
                });

            modelBuilder.Entity("MusicFree.Models.Musician", b =>
                {
                    b.Navigation("Albumns");

                    b.Navigation("Songs");

                    b.Navigation("collaboration_albumns");

                    b.Navigation("collaboration_songs");

                    b.Navigation("genres");

                    b.Navigation("liked_by");

                    b.Navigation("listened_by");
                });

            modelBuilder.Entity("MusicFree.Models.Playlist", b =>
                {
                    b.Navigation("songs");
                });

            modelBuilder.Entity("MusicFree.Models.Song", b =>
                {
                    b.Navigation("extra_authors");

                    b.Navigation("genres");

                    b.Navigation("liked_by");

                    b.Navigation("playllists");

                    b.Navigation("song_views");

                    b.Navigation("tags");
                });
#pragma warning restore 612, 618
        }
    }
}
